server:
  port: 8001
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie?characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123