# spring配置
spring:
  # 应用名称
  application:
    name: PageViewCountDemo
  datasource:
    # 数据源名称
    name: defaultDataSource
    # 数据库驱动：
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&allowMultiQueries=true
    # 数据库用户名&密码：
    username: root
    password: 123
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    excluded-view-names: ''
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    static-path-pattern: /static/**
  redis:
    host: 192.168.109.110
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        #最大连接数 默认8
        max-active: 8
        #最大连接阻塞时间
        max-wait: 1000ms
        #最大空闲连接，默认8
        max-idle: 200
        min-idle: 5
  rabbitmq:
    host: 192.168.109.110
    port: 5672
    username: admin
    password: admin
---
# Mybatis属性配置
mybatis:
  mapper-locations: classpath:mapper/*xml
  type-aliases-package: com.fyj.pageviewcountdemo.entity
---
# 应用服务 WEB 访问端口
server:
  port: 8080